# Generated by Django 4.1.2 on 2022-11-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
