# Generated by Django 4.1.2 on 2023-04-18 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_listing_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="userBid",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="userBiddings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
