# Generated by Django 5.0 on 2023-12-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_alter_category_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
